configs:
- id: '0.0'
  operations:
  - type: update
    segment_index: '001.0000'
    new_tarteel_transcript:
    - أعوذ بالله من الشيطان الرجيم
  - type: update
    segment_index: '004.0035'
    new_tarteel_transcript:
    - فَإِن كَانَ لَكُمْ وَلَدٌ فَلَهُنَّ الثُّمُنُ مِمَّا تَرَكْتُم
  - type: update
    segment_index: '006.0268'
    new_tarteel_transcript:
    - وَمِنَ الْإِبِلِ اثْنَيْنِ وَمِنَ الْبَقَرِ اثْنَيْنِ
  - type: update
    segment_index: '008.0013'
    new_tarteel_transcript:
    - وَمَا النَّصْرُ إِلَّا مِنْ عِندِ اللَّهِ
  - type: update
    segment_index: '013.0002'
    new_tarteel_transcript:
    - المر
  - type: update
    segment_index: '014.0001'
    new_tarteel_transcript:
    - الر
  - type: update
    segment_index: '024.0049'
    new_tarteel_transcript:
    - أَوْ آبَاءِ بُعُولَتِهِنَّ أَوْ أَبْنَائِهِنَّ أَوْ أَبْنَاءِ بُعُولَتِهِنَّ
      أَوْ إِخْوَانِهِنَّ أَوْ بَنِي إِخْوَانِهِنَّ أَوْ بَنِي أَخَوَاتِهِنَّ أَوْ
      نِسَائِهِنَّ أَوْ مَا مَلَكَتْ أَيْمَانُهُنَّ
  - type: update
    segment_index: '027.0001'
    new_tarteel_transcript:
    - طس
  - type: update
    segment_index: '029.0005'
    new_audio_file: 0.0/029_0005.wav
    new_tarteel_transcript:
    - سَاءَ مَا يَحْكُمُونَ
  - type: update
    segment_index: '048.0051'
    new_tarteel_transcript:
    - مُّحَمَّدٌ رَّسُولُ اللَّهِ
  - type: update
    segment_index: '050.0001'
    new_tarteel_transcript:
    - ق
  - type: delete
    segment_index: '022.0055'
  - type: update
    segment_index: '022.0054'
    new_end_seconds: 823.345
    new_tarteel_transcript:
    - لَن يَنَالَ اللَّهَ لُحُومُهَا وَلَا دِمَاؤُهَا وَلَٰكِن يَنَالُهُ التَّقْوَىٰ
      مِنكُمْ
  - type: delete
    segment_index: '057.0060'
  - type: update
    segment_index: '057.0059'
    new_end_seconds: 864.155
    new_tarteel_transcript:
    - لِّئَلَّا يَعْلَمَ أَهْلُ الْكِتَابِ أَلَّا يَقْدِرُونَ عَلَىٰ شَيْءٍ مِّن فَضْلِ
      اللَّهِ وَأَنَّ الْفَضْلَ بِيَدِ اللَّهِ يُؤْتِيهِ مَن يَشَاءُ وَاللَّهُ
- id: '0.1'
  operations:
  - type: update
    segment_index: '002.0522'
    new_tarteel_transcript:
    - وَلَا تَنكِحُوا الْمُشْرِكَاتِ حَتَّىٰ يُؤْمِنَّ
  - type: update
    segment_index: '002.0588'
    new_tarteel_transcript:
    - ' وَأَن تَعْفُوا أَقْرَبُ لِلتَّقْوَىٰ'
  - type: update
    segment_index: '004.0024'
    new_tarteel_transcript:
    - ' فَإِن كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ'
  - type: update
    segment_index: '004.0028'
    new_tarteel_transcript:
    - فَإِن كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ
  - type: update
    segment_index: '004.0433'
    new_tarteel_transcript:
    - فَإِن كَانَتَا اثْنَتَيْنِ فَلَهُمَا الثُّلُثَانِ مِمَّا تَرَكَ
  - type: update
    segment_index: '006.0337'
    new_tarteel_transcript:
    - ' وَمِنَ الْإِبِلِ اثْنَيْنِ وَمِنَ الْبَقَرِ اثْنَيْنِ'
  - type: update
    segment_index: '008.0015'
    new_tarteel_transcript:
    - ' وَمَا النَّصْرُ إِلَّا مِنْ عِندِ اللَّهِ'
  - type: update
    segment_index: '010.0000'
    new_tarteel_transcript:
    - أعوذ بالله من الشيطان الرجيم
  - type: update
    segment_index: '011.0000'
    new_tarteel_transcript:
    - أعوذ بالله من الشيطان الرجيم
  - type: update
    segment_index: '012.0059'
    new_tarteel_transcript:
    - فَلَمَّا سَمِعَتْ بِمَكْرِهِنَّ أَرْسَلَتْ إِلَيْهِنَّ وَأَعْتَدَتْ لَهُنَّ
      مُتَّكَأً وَآتَتْ كُلَّ وَاحِدَةٍ مِّنْهُنَّ سِكِّينًا وَقَالَتِ اخْرُجْ عَلَيْهِنَّ
  - type: update
    segment_index: '021.0126'
    new_tarteel_transcript:
    - ' كُلٌّ مِّنَ الصَّابِرِينَ'
  - type: update
    segment_index: '024.0138'
    new_tarteel_transcript:
    - ' ثَلَاثُ عَوْرَاتٍ لَّكُمْ'
  - type: update
    segment_index: '024.0149'
    new_tarteel_transcript:
    - لَّيْسَ عَلَى الْأَعْمَىٰ حَرَجٌ وَلَا عَلَى الْأَعْرَجِ حَرَجٌ وَلَا عَلَى
      الْمَرِيضِ حَرَجٌ وَلَا عَلَىٰ أَنفُسِكُمْ أَن تَأْكُلُوا مِن بُيُوتِكُمْ
  - type: update
    segment_index: '027.0001'
    new_tarteel_transcript:
    - طس
  - type: update
    segment_index: '033.0111'
    new_tarteel_transcript:
    - يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَدْخُلُوا بُيُوتَ النَّبِيِّ إِلَّا أَن
      يُؤْذَنَ لَكُمْ إِلَىٰ طَعَامٍ غَيْرَ نَاظِرِينَ إِنَاهُ وَلَٰكِنْ إِذَا دُعِيتُمْ
      فَادْخُلُوا
  - type: update
    segment_index: '060.0029'
    new_tarteel_transcript:
    - ' وَآتُوهُم مَّا أَنفَقُوا'
  - type: update
    segment_index: '073.0030'
    new_tarteel_transcript:
    - وَاسْتَغْفِرُوا اللَّهَ
  - type: delete
    segment_index: '004.0162'
  - type: update
    segment_index: '004.0161'
    new_end_seconds: 2496.4
    new_tarteel_transcript:
    - يُرِيدُونَ أَن يَتَحَاكَمُوا إِلَى الطَّاغُوتِ وَقَدْ أُمِرُوا أَن يَكْفُرُوا
      بِهِ وَيُرِيدُ الشَّيْطَانُ أَن يُضِلَّهُمْ ضَلَالًا بَعِيدًا
  - type: delete
    segment_index: '009.0181'
  - type: update
    segment_index: '009.0180'
    new_end_seconds: 3262.205
    new_tarteel_transcript:
    - الَّذِينَ يَلْمِزُونَ الْمُطَّوِّعِينَ مِنَ الْمُؤْمِنِينَ فِي الصَّدَقَاتِ
      وَالَّذِينَ لَا يَجِدُونَ إِلَّا جُهْدَهُمْ فَيَسْخَرُونَ مِنْهُمْ سَخِرَ اللَّهُ
      مِنْهُمْ
  - type: delete
    segment_index: '031.0041'
  - type: update
    segment_index: '031.0040'
    new_end_seconds: 603.19
    new_tarteel_transcript:
    - ' وَمِنَ النَّاسِ مَن يُجَادِلُ فِي اللَّهِ بِغَيْرِ عِلْمٍ وَلَا هُدًى وَلَا
      كِتَابٍ مُّنِيرٍ'
- id: '0.2'
  operations:
  - type: update
    segment_index: '002.0225'
    new_tarteel_transcript:
    - ' فَاعْفُوا وَاصْفَحُوا حَتَّىٰ يَأْتِيَ اللَّهُ بِأَمْرِهِ'
  - type: update
    segment_index: '002.0400'
    new_tarteel_transcript:
    - ' ثُمَّ أَتِمُّوا الصِّيَامَ إِلَى اللَّيْلِ'
  - type: update
    segment_index: '003.0138'
    new_tarteel_transcript:
    - هَا أَنتُمْ هَٰؤُلَاءِ حَاجَجْتُمْ فِيمَا لَكُم بِهِ عِلْمٌ فَلِمَ تُحَاجُّونَ
      فِيمَا لَيْسَ لَكُم بِهِ عِلْمٌ
  - type: update
    segment_index: '004.0036'
    new_tarteel_transcript:
    - ' وَلَهُنَّ الرُّبُعُ مِمَّا تَرَكْتُمْ إِن لَّمْ يَكُن لَّكُمْ وَلَدٌ'
  - type: update
    segment_index: '004.0352'
    new_tarteel_transcript:
    - وَقَدْ نَزَّلَ عَلَيْكُمْ فِي الْكِتَابِ أَنْ إِذَا سَمِعْتُمْ آيَاتِ اللَّهِ
      يُكْفَرُ بِهَا وَيُسْتَهْزَأُ بِهَا فَلَا تَقْعُدُوا مَعَهُمْ حَتَّىٰ يَخُوضُوا
      فِي حَدِيثٍ غَيْرِهِ
  - type: update
    segment_index: '006.0234'
    new_tarteel_transcript:
    - وَمَا لَكُمْ أَلَّا تَأْكُلُوا مِمَّا ذُكِرَ اسْمُ اللَّهِ عَلَيْهِ وَقَدْ فَصَّلَ
      لَكُم مَّا حَرَّمَ عَلَيْكُمْ إِلَّا مَا اضْطُرِرْتُمْ إِلَيْهِ
  - type: update
    segment_index: '006.0292'
    new_tarteel_transcript:
    - وَمِنَ الْإِبِلِ اثْنَيْنِ وَمِنَ الْبَقَرِ اثْنَيْنِ
  - type: update
    segment_index: '008.0015'
    new_tarteel_transcript:
    - ' وَمَا النَّصْرُ إِلَّا مِنْ عِندِ اللَّهِ'
  - type: update
    segment_index: '008.0043'
    new_tarteel_transcript:
    - وَاذْكُرُوا إِذْ أَنتُمْ قَلِيلٌ مُّسْتَضْعَفُونَ فِي الْأَرْضِ تَخَافُونَ أَن
      يَتَخَطَّفَكُمُ النَّاسُ فَآوَاكُمْ وَأَيَّدَكُم بِنَصْرِهِ
  - type: update
    segment_index: '015.0001'
    new_tarteel_transcript:
    - الر
  - type: update
    segment_index: '018.0122'
    new_tarteel_transcript:
    - وَكَانَ أَبُوهُمَا صَالِحًا فَأَرَادَ رَبُّكَ أَن يَبْلُغَا أَشُدَّهُمَا وَيَسْتَخْرِجَا
      كَنزَهُمَا رَحْمَةً مِّن رَّبِّكَ
  - type: update
    segment_index: '027.0001'
    new_tarteel_transcript:
    - طس
  - type: update
    segment_index: '028.0096'
    new_tarteel_transcript:
    - قَالَ الَّذِينَ حَقَّ عَلَيْهِمُ الْقَوْلُ رَبَّنَا هَٰؤُلَاءِ الَّذِينَ أَغْوَيْنَا
      أَغْوَيْنَاهُمْ كَمَا غَوَيْنَا تَبَرَّأْنَا إِلَيْكَ
  - type: update
    segment_index: '033.0069'
    new_tarteel_transcript:
    - وَالصَّابِرِينَ وَالصَّابِرَاتِ وَالْخَاشِعِينَ وَالْخَاشِعَاتِ وَالْمُتَصَدِّقِينَ
      وَالْمُتَصَدِّقَاتِ وَالصَّائِمِين
  - type: update
    segment_index: '033.0121'
    new_tarteel_transcript:
    - وَاتَّقِينَ اللَّهَ
  - type: update
    segment_index: '039.0050'
    new_tarteel_transcript:
    - أَفَمَن شَرَحَ اللَّهُ صَدْرَهُ لِلْإِسْلَامِ فَهُوَ عَلَىٰ نُورٍ مِّن رَّبِّهِ
      فَوَيْلٌ لِّلْقَاسِيَةِ قُلُوبُهُم مِّن ذِكْرِ اللَّهِ
  - type: update
    segment_index: '040.0013'
    new_tarteel_transcript:
    - وَمَن تَقِ السَّيِّئَاتِ يَوْمَئِذٍ فَقَدْ رَحِمْتَهُ
  - type: update
    segment_index: '040.0107'
    new_tarteel_transcript:
    - هُوَ الَّذِي خَلَقَكُم مِّن تُرَابٍ ثُمَّ مِن نُّطْفَةٍ ثُمَّ مِنْ عَلَقَةٍ
      ثُمَّ يُخْرِجُكُمْ طِفْلًا ثُمَّ لِتَبْلُغُوا أَشُدَّكُمْ
  - type: update
    segment_index: '048.0066'
    new_tarteel_transcript:
    - ' وَمَثَلُهُمْ فِي الْإِنجِيلِ كَزَرْعٍ أَخْرَجَ شَطْأَهُ فَآزَرَهُ فَاسْتَغْلَظَ
      فَاسْتَوَىٰ عَلَىٰ سُوقِهِ يُعْجِبُ الزُّرَّاعَ لِيَغِيظَ بِهِمُ الْكُفَّارَ'
  - type: update
    segment_index: '053.0035'
    new_tarteel_transcript:
    - الَّذِينَ يَجْتَنِبُونَ كَبَائِرَ الْإِثْمِ وَالْفَوَاحِشَ إِلَّا اللَّمَمَ
  - type: update
    segment_index: '066.0011'
    new_tarteel_transcript:
    - مُسْلِمَاتٍ مُّؤْمِنَاتٍ قَانِتَاتٍ تَائِبَاتٍ عَابِدَاتٍ سَائِحَاتٍ ثَيِّبَاتٍ
      وَأَبْكَارًا
  - type: update
    segment_index: '095.0000'
    new_tarteel_transcript:
    - أعوذ بالله من الشيطان الرجيم
  - type: delete
    segment_index: '002.0114'
  - type: delete
    segment_index: '011.0045'
  - type: delete
    segment_index: '042.0021'
  - type: delete
    segment_index: '042.0020'
