configs:
- id: '0.0'
  operations:
  - type: update
    segment_index: '003.0261'
    new_tarteel_transcript:
    - بَلِ اللَّهُ مَوْلَاكُمْ وَهُوَ خَيْرُ النَّاصِرِينَ
  - type: update
    segment_index: '004.0037'
    new_tarteel_transcript:
    - وَإِن كَانَ رَجُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ
      فَلِكُلِّ وَاحِدٍ مِّنْهُمَا السُّدُسُ
  - type: update
    segment_index: '019.0081'
    new_tarteel_transcript:
    - ' كَانَ عَلَىٰ رَبِّكَ حَتْمًا مَّقْضِيًّا'
  - type: update
    segment_index: '024.0120'
    new_tarteel_transcript:
    - أَوْ بُيُوتِ إِخْوَانِكُمْ أَوْ بُيُوتِ أَخَوَاتِكُمْ أَوْ بُيُوتِ أَعْمَامِكُمْ
      أَوْ بُيُوتِ عَمَّاتِكُمْ أَوْ بُيُوتِ أَخْوَالِكُمْ أَوْ بُيُوتِ خَالَاتِكُمْ
- id: '0.1'
  operations:
  - type: update
    segment_index: '024.0059'
    new_tarteel_transcript:
    - ' وَلَا يُبْدِينَ زِينَتَهُنَّ إِلَّا لِبُعُولَتِهِنَّ أَوْ آبَائِهِنَّ أَوْ
      آبَاءِ بُعُولَتِهِنَّ أَوْ أَبْنَائِهِنَّ'
  - type: update
    segment_index: '024.0060'
    new_tarteel_transcript:
    - أَوْ أَبْنَائِهِنَّ أَوْ أَبْنَاءِ بُعُولَتِهِنَّ أَوْ إِخْوَانِهِنَّ أَوْ بَنِي
      إِخْوَانِهِنَّ أَوْ بَنِي أَخَوَاتِهِنَّ
  - type: delete
    segment_index: '024.0062'
  - type: update
    segment_index: '024.0061'
    new_end_seconds: 1130.42
    new_tarteel_transcript:
    - أَوْ بَنِي أَخَوَاتِهِنَّ أَوْ نِسَائِهِنَّ أَوْ مَا مَلَكَتْ أَيْمَانُهُنَّ
      أَوِ التَّابِعِينَ غَيْرِ أُولِي الْإِرْبَةِ مِنَ الرِّجَالِ أَوِ الطِّفْلِ
  - type: insert
    segment_index: '084.0015'
    new_start_seconds: 134.2
    new_end_seconds: 136.4
    new_tarteel_transcript:
    - بَلَىٰ
  - type: update
    segment_index: '006.0148'
    new_tarteel_transcript:
    - كَالَّذِي اسْتَهْوَتْهُ الشَّيَاطِينُ فِي الْأَرْضِ حَيْرَانَ لَهُ أَصْحَابٌ
      يَدْعُونَهُ إِلَى الْهُدَى ائْتِنَا
  - type: update
    segment_index: '004.0025'
    new_tarteel_transcript:
    - وَإِن كَانَتْ وَاحِدَةً فَلَهَا النِّصْفُ
  - type: update
    segment_index: '004.0039'
    new_tarteel_transcript:
    - ' وَإِن كَانَ رَجُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ
      فَلِكُلِّ وَاحِدٍ مِّنْهُمَا السُّدُسُ'
