configs:
- id: '0.0'
  operations:
  - type: update
    segment_index: '000.0133'
    new_tarteel_transcript:
    - هِيَ حَسْبُهُمْ
    sample_rate: 16000
  - type: update
    segment_index: '008.0039'
    new_audio_file: 0.0/008_0039.wav
    sample_rate: 16000
  - type: delete
    segment_index: '008.0040'
    sample_rate: 16000
  - type: delete
    segment_index: '009.0042'
    sample_rate: 16000
  - type: delete
    segment_index: '009.0043'
    sample_rate: 16000
  - type: update
    segment_index: '009.0133'
    new_tarteel_transcript:
    - هِيَ حَسْبُهُمْ
    sample_rate: 16000
  - type: update
    segment_index: '011.0205'
    new_audio_file: 0.0/011.0205.wav
    sample_rate: 16000
  - type: delete
    segment_index: '011.0206'
    sample_rate: 16000
  - type: update
    segment_index: '016.0047'
    new_audio_file: 0.0/016_0047.wav
    sample_rate: 16000
  - type: delete
    segment_index: '016.0048'
    sample_rate: 16000
  - type: update
    segment_index: '016.0165'
    new_audio_file: 0.0/016_0165.wav
    new_tarteel_transcript:
    - إِنَّمَا يَفْتَرِي الْكَذِبَ الَّذِينَ لَا يُؤْمِنُونَ بِآيَاتِ اللَّهِ وَأُولَٰئِكَ
      هُمُ الْكَاذِبُونَ ‎
    sample_rate: 16000
  - type: delete
    segment_index: '016.0166'
    sample_rate: 16000
  - type: update
    segment_index: '019.0069'
    new_audio_file: 0.0/019_0069.wav
    sample_rate: 16000
  - type: delete
    segment_index: '019.0070'
    sample_rate: 16000
  - type: update
    segment_index: '026.0146'
    new_audio_file: 0.0/026_0146.wav
    sample_rate: 16000
  - type: delete
    segment_index: '026.0147'
    sample_rate: 16000
  - type: update
    segment_index: '037.0181'
    new_audio_file: 0.0/037_0181.wav
    sample_rate: 16000
  - type: delete
    segment_index: '037.0182'
    sample_rate: 16000
  - type: update
    segment_index: '039.0097'
    new_audio_file: 0.0/039_0097.wav
    sample_rate: 16000
  - type: delete
    segment_index: '039.0098'
    sample_rate: 16000
  - type: update
    segment_index: '042.0032'
    new_audio_file: 0.0/042_0032.wav
    sample_rate: 16000
  - type: delete
    segment_index: '042.0033'
    sample_rate: 16000
  - type: update
    segment_index: '056.0096'
    new_audio_file: 0.0/056_0096.wav
    new_tarteel_transcript:
    - فَسَبِّح بِاسمِ رَبِّكَ العَظيمِ
    sample_rate: 16000
  - type: delete
    segment_index: '056.0097'
    sample_rate: 16000
  - type: delete
    segment_index: '059.0029'
    sample_rate: 16000
  - type: update
    segment_index: '059.0028'
    new_audio_file: 0.0/059_0028.wav
    sample_rate: 16000
  - type: delete
    segment_index: '068.0049'
    sample_rate: 16000
  - type: update
    segment_index: '068.0048'
    new_audio_file: 0.0/068_0048.wav
    sample_rate: 16000
  - type: delete
    segment_index: '096.0013'
    sample_rate: 16000
  - type: update
    segment_index: '096.0012'
    new_audio_file: 0.0/096_0012.wav
    new_tarteel_transcript:
    - أَو أَمَرَ بِالتَّقوىٰ
    sample_rate: 16000
  - type: update
    segment_index: '053.0034'
    new_tarteel_transcript:
    - الَّذِينَ يَجْتَنِبُونَ كَبَائِرَ الْإِثْمِ وَالْفَوَاحِشَ إِلَّا اللَّمَمَ
    sample_rate: 16000
- id: '0.1'
  operations:
  - type: delete
    segment_index: '004.0062'
    sample_rate: 16000
  - type: update
    segment_index: '004.0061'
    new_audio_file: 0.1/004_0061.wav
    new_tarteel_transcript:
    - وَإِن أَرَدتُمُ استِبدالَ زَوجٍ مَكانَ زَوجٍ وَآتَيتُم إِحداهُنَّ قِنطارًا فَلا
      تَأخُذوا مِنهُ شَيئًا
    sample_rate: 16000
  - type: delete
    segment_index: '006.0211'
    sample_rate: 16000
  - type: update
    segment_index: '006.0210'
    new_audio_file: 0.1/006_0210.wav
    new_tarteel_transcript:
    - ' لَقَد تَقَطَّعَ بَينَكُم وَضَلَّ عَنكُم ما كُنتُم تَزعُمونَ'
    sample_rate: 16000
  - type: delete
    segment_index: '006.0376'
    sample_rate: 16000
  - type: update
    segment_index: '006.0375'
    new_audio_file: 0.1/006_0375.wav
    sample_rate: 16000
  - type: delete
    segment_index: '009.0036'
    sample_rate: 16000
  - type: update
    segment_index: '009.0035'
    new_audio_file: 0.1/009_0035.wav
    new_tarteel_transcript:
    - أَم حَسِبتُم أَن تُترَكوا وَلَمّا يَعلَمِ اللَّهُ الَّذينَ جاهَدوا مِنكُم وَلَم
      يَتَّخِذوا
    sample_rate: 16000
  - type: delete
    segment_index: '009.0249'
    sample_rate: 16000
  - type: update
    segment_index: '009.0248'
    new_audio_file: 0.1/009_0248.wav
    new_tarteel_transcript:
    - وَالَّذينَ اتَّخَذوا مَسجِدًا ضِرارًا وَكُفرًا وَتَفريقًا بَينَ المُؤمِنينَ
      وَإِرصادًا لِمَن حارَبَ اللَّهَ وَرَسولَهُ مِن قَبلُ وَلَيَحلِفُنَّ
    sample_rate: 16000
  - type: delete
    segment_index: '012.0099'
    sample_rate: 16000
  - type: update
    segment_index: '012.0098'
    new_audio_file: 0.1/012_0098.wav
    new_tarteel_transcript:
    - ثُمَّ يَأتي مِن بَعدِ ذٰلِكَ سَبعٌ شِدادٌ يَأكُلنَ ما قَدَّمتُم لَهُنَّ إِلّا
      قَليلًا مِمّا تُحصِنونَ
    sample_rate: 16000
  - type: update
    segment_index: '012.0138'
    new_tarteel_transcript:
    - ' عَلَيهِ تَوَكَّلتُ'
    sample_rate: 16000
  - type: delete
    segment_index: '028.0065'
    sample_rate: 16000
  - type: update
    segment_index: '028.0064'
    new_audio_file: 0.1/028_0064.wav
    new_tarteel_transcript:
    - وَأَخي هارونُ هُوَ أَفصَحُ مِنّي لِسانًا فَأَرسِلهُ مَعِيَ رِدءًا يُصَدِّقُني
    sample_rate: 16000
  - type: update
    segment_index: '038.0079'
    new_tarteel_transcript:
    - 'هَٰذَا '
    sample_rate: 16000
  - type: delete
    segment_index: '043.0030'
    sample_rate: 16000
  - type: update
    segment_index: '043.0029'
    new_audio_file: 0.1/043_0029.wav
    sample_rate: 16000
  - type: delete
    segment_index: '043.0127'
    sample_rate: 16000
  - type: update
    segment_index: '043.0126'
    new_audio_file: 0.1/043_0126.wav
    new_tarteel_transcript:
    - فَاصْفَحْ عَنْهُمْ وَقُلْ سَلَامٌ
    sample_rate: 16000
  - type: update
    segment_index: '053.0037'
    new_tarteel_transcript:
    - الَّذِينَ يَجْتَنِبُونَ كَبَائِرَ الْإِثْمِ وَالْفَوَاحِشَ إِلَّا اللَّمَمَ
    sample_rate: 16000
