configs:
- id: '0.2'
  operations:
  - type: update
    segment_index: '004.0356'
    new_tarteel_transcript:
    - فَإِن كَانَ لَكُمْ فَتْحٌ مِّنَ اللَّهِ قَالُوا أَلَمْ نَكُن مَّعَكُمْ وَإِن
      كَانَ لِلْكَافِرِينَ نَصِيبٌ قَالُوا أَلَمْ نَسْتَحْوِذْ عَلَيْكُمْ
  - type: update
    segment_index: '012.0119'
    new_tarteel_transcript:
    - وَلَمَّا دَخَلُوا مِنْ حَيْثُ أَمَرَهُمْ أَبُوهُم مَّا كَانَ يُغْنِي عَنْهُم
      مِّنَ اللَّهِ مِن شَيْءٍ إِلَّا حَاجَةً فِي نَفْسِ يَعْقُوبَ قَضَاهَا
  - type: update
    segment_index: '067.0012'
    new_tarteel_transcript:
    - قَالُوا بَلَىٰ قَدْ جَاءَنَا نَذِيرٌ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ اللَّهُ
      مِن شَيْءٍ إِنْ أَنتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ
- id: '2.0'
  operations:
  - type: update
    segment_index: '009.0177'
    new_tarteel_transcript:
    - فَإِن رَّجَعَكَ اللَّهُ إِلَىٰ طَائِفَةٍ مِّنْهُمْ فَاسْتَأْذَنُوكَ لِلْخُرُوجِ
      فَقُل لَّن تَخْرُجُوا مَعِيَ أَبَدًا وَلَن تُقَاتِلُوا مَعِيَ عَدُوًّا
  - type: update
    segment_index: '004.0052'
    new_tarteel_transcript:
    - وَلَيْسَتِ التَّوْبَةُ لِلَّذِينَ يَعْمَلُونَ السَّيِّئَاتِ حَتَّىٰ إِذَا حَضَرَ
      أَحَدَهُمُ الْمَوْتُ قَالَ إِنِّي تُبْتُ الْآنَ وَلَا الَّذِينَ يَمُوتُونَ وَهُمْ
      كُفَّارٌ
  - type: update
    segment_index: '049.0046'
    new_tarteel_transcript:
    - ' قُل لَّا تَمُنُّوا عَلَيَّ إِسْلَامَكُم بَلِ اللَّهُ يَمُنُّ عَلَيْكُمْ أَنْ
      هَدَاكُمْ لِلْإِيمَانِ إِن كُنتُمْ صَادِقِينَ'
  - type: update
    segment_index: '067.0012'
    new_tarteel_transcript:
    - قَالُوا بَلَىٰ قَدْ جَاءَنَا نَذِيرٌ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ اللَّهُ
      مِن شَيْءٍ إِنْ أَنتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ
- id: '7.0'
  operations:
  - type: update
    segment_index: '002.0561'
    new_tarteel_transcript:
    - فَلَمَّا فَصَلَ طَالُوتُ بِالْجُنُودِ قَالَ إِنَّ اللَّهَ مُبْتَلِيكُم بِنَهَرٍ
      فَمَن شَرِبَ مِنْهُ فَلَيْسَ مِنِّي وَمَن لَّمْ يَطْعَمْهُ فَإِنَّهُ مِنِّي
      إِلَّا مَنِ اغْتَرَفَ غُرْفَةً بِيَدِهِ
- id: '13.0'
  operations:
  - type: update
    segment_index: '002.0558'
    new_tarteel_transcript:
    - فَلَمَّا فَصَلَ طَالُوتُ بِالْجُنُودِ قَالَ إِنَّ اللَّهَ مُبْتَلِيكُم بِنَهَرٍ
      فَمَن شَرِبَ مِنْهُ فَلَيْسَ مِنِّي وَمَن لَّمْ يَطْعَمْهُ فَإِنَّهُ مِنِّي
      إِلَّا مَنِ اغْتَرَفَ غُرْفَةً بِيَدِهِ
