configs:
- id: '0.2'
  operations:
  - type: update
    segment_index: '004.0356'
    new_tarteel_transcript:
    - فَإِن كَانَ لَكُمْ فَتْحٌ مِّنَ اللَّهِ قَالُوا أَلَمْ نَكُن مَّعَكُمْ وَإِن
      كَانَ لِلْكَافِرِينَ نَصِيبٌ قَالُوا أَلَمْ نَسْتَحْوِذْ عَلَيْكُمْ
  - type: update
    segment_index: '012.0119'
    new_tarteel_transcript:
    - وَلَمَّا دَخَلُوا مِنْ حَيْثُ أَمَرَهُمْ أَبُوهُم مَّا كَانَ يُغْنِي عَنْهُم
      مِّنَ اللَّهِ مِن شَيْءٍ إِلَّا حَاجَةً فِي نَفْسِ يَعْقُوبَ قَضَاهَا
  - type: update
    segment_index: '067.0012'
    new_tarteel_transcript:
    - قَالُوا بَلَىٰ قَدْ جَاءَنَا نَذِيرٌ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ اللَّهُ
      مِن شَيْءٍ إِنْ أَنتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ
- id: '2.0'
  operations:
  - type: update
    segment_index: '004.0052'
    new_tarteel_transcript:
    - وَلَيْسَتِ التَّوْبَةُ لِلَّذِينَ يَعْمَلُونَ السَّيِّئَاتِ حَتَّىٰ إِذَا حَضَرَ
      أَحَدَهُمُ الْمَوْتُ قَالَ إِنِّي تُبْتُ الْآنَ وَلَا الَّذِينَ يَمُوتُونَ وَهُمْ
      كُفَّارٌ
  - type: update
    segment_index: '009.0177'
    new_tarteel_transcript:
    - فَإِن رَّجَعَكَ اللَّهُ إِلَىٰ طَائِفَةٍ مِّنْهُمْ فَاسْتَأْذَنُوكَ لِلْخُرُوجِ
      فَقُل لَّن تَخْرُجُوا مَعِيَ أَبَدًا وَلَن تُقَاتِلُوا مَعِيَ عَدُوًّا
  - type: update
    segment_index: '049.0046'
    new_tarteel_transcript:
    - ' قُل لَّا تَمُنُّوا عَلَيَّ إِسْلَامَكُم بَلِ اللَّهُ يَمُنُّ عَلَيْكُمْ أَنْ
      هَدَاكُمْ لِلْإِيمَانِ إِن كُنتُمْ صَادِقِينَ'
  - type: update
    segment_index: '067.0012'
    new_tarteel_transcript:
    - قَالُوا بَلَىٰ قَدْ جَاءَنَا نَذِيرٌ فَكَذَّبْنَا وَقُلْنَا مَا نَزَّلَ اللَّهُ
      مِن شَيْءٍ إِنْ أَنتُمْ إِلَّا فِي ضَلَالٍ كَبِيرٍ
- id: '7.0'
  operations:
  - type: update
    segment_index: '002.0561'
    new_tarteel_transcript:
    - فَلَمَّا فَصَلَ طَالُوتُ بِالْجُنُودِ قَالَ إِنَّ اللَّهَ مُبْتَلِيكُم بِنَهَرٍ
      فَمَن شَرِبَ مِنْهُ فَلَيْسَ مِنِّي وَمَن لَّمْ يَطْعَمْهُ فَإِنَّهُ مِنِّي
      إِلَّا مَنِ اغْتَرَفَ غُرْفَةً بِيَدِهِ
  - type: update
    segment_index: '005.0010'
    new_tarteel_transcript:
    - حُرِّمَتْ عَلَيْكُمُ الْمَيْتَةُ وَالدَّمُ وَلَحْمُ الْخِنزِيرِ وَمَا أُهِلَّ
      لِغَيْرِ اللَّهِ بِهِ وَالْمُنْخَنِقَةُ وَالْمَوْقُوذَةُ وَالْمُتَرَدِّيَةُ
      وَالنَّطِيحَةُ وَمَا أَكَلَ السَّبُعُ إِلَّا مَا ذَكَّيْتُمْ وَمَا ذُبِحَ عَلَى
      النُّصُبِ وَأَن تَسْتَقْسِمُوا بِالْأَزْلَامِ
- id: '13.0'
  operations:
  - type: update
    segment_index: '002.0558'
    new_tarteel_transcript:
    - فَلَمَّا فَصَلَ طَالُوتُ بِالْجُنُودِ قَالَ إِنَّ اللَّهَ مُبْتَلِيكُم بِنَهَرٍ
      فَمَن شَرِبَ مِنْهُ فَلَيْسَ مِنِّي وَمَن لَّمْ يَطْعَمْهُ فَإِنَّهُ مِنِّي
      إِلَّا مَنِ اغْتَرَفَ غُرْفَةً بِيَدِهِ
- id: '29.0'
  operations:
  - type: update
    segment_index: '003.0174'
    new_tarteel_transcript:
    - بَلَىٰ
- id: '30.0'
  operations:
  - type: update
    segment_index: '038.0088'
    new_tarteel_transcript:
    - هَٰذَا
  - type: update
    segment_index: '047.0008'
    new_tarteel_transcript:
    - ذَٰلِكَ
- id: '25.0'
  operations:
  - type: insert
    segment_index: '018.0044'
    new_end_seconds: 365.59
    new_tarteel_transcript:
    - إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ إِنَّا لَا نُضِيعُ أَجْرَ مَنْ
      أَحْسَنَ عَمَلًا
  - type: update
    segment_index: '018.0044'
    new_start_seconds: 365.59
    new_tarteel_transcript:
    - أُولَئِكَ لَهُمْ جَنَّاتُ عَدْلٍ تَجْرِي مِنْ تَحْتِهِمُ الْأَنْهَارُ يُحَلَّوْنَ
      فِيهَا مِنْ أَسَاوِرَ مِنْ ذَهَبٍ وَيَلْبَسُونَ فِيهَا بَلْ خُضْرًا مِنْ سُنْدُسٍ
      وَإِسْتَبْرَقٍ مُتَّكِئِينَ فِيهَا عَلَى الْأَرَائِكِ نِعْمَ الثَّوَابُ وَحَسُنَتْ
      مُرْتَفَقًا
  - type: insert
    segment_index: '028.0088'
    new_end_seconds: 869.0
    new_tarteel_transcript:
    - 'وَنَزَعْنَا مِنْ كُلِّ أُمَّةٍ شَهِيدًا فَقُلْنَا هَاتُوا بُرْهَانَكُمْ فَعَلِمُوا
      أَنَّ الْحَقَّ لِلَّهِ وَضَلَّ عَنْهُمْ مَا كَانُوا يَفْتَرُونَ '
  - type: update
    segment_index: '028.0088'
    new_start_seconds: 869.0
    new_tarteel_transcript:
    - إِنَّ قَارُونَ كَانَ مِنْ قَوْمِ مُوسَى فَبَغَوا عَلَيْهِمْ وَآتَيْنَاهُ مِنَ
      الْكُنُوزِ مَا إِنَّ مَفَاتِحَهُ لَتَنُوءُ بِالْعُصْبَةِ أُولِي الْقُوَّةِ إِذْ
      قَالَ لَهُ قَوْمُهُ لَا تَفْرَحْتَ
  - type: insert
    segment_index: '038.0027'
    new_end_seconds: 180.6
    new_tarteel_transcript:
    - فَغَفَرْنَا لَهُ ذَٰلِكَ وَإِنَّ لَهُ عِندَنَا لَزُلْفَىٰ وَحُسْنَ مَآبٍ
  - type: update
    segment_index: '038.0027'
    new_start_seconds: 180.6
    new_tarteel_transcript:
    - يَا دَاوُودُ إِنَّ جَعَلْنَاكَ خَلِفَةً فِي الْأَرْضِ فَاحْكُمْ بَيْنَ النَّاسِ
      بِالْحَقِّ وَلَا تَتَّبِعِ الْهَوَى فَيُضِلَّكَ عَنْ سَبِيلِ اللَّهِ إِنَّ الَّذِينَ
      يَضِلُّونَ عَنْ سَبِيلِ اللَّهِ لَهُمْ عَذَابٌ شَدِيدٌ بِمَا نَسُوا يَوْمَ الْحِسَابِ
  - type: insert
    segment_index: '047.0027'
    new_end_seconds: 262.46
    new_tarteel_transcript:
    - 'وَيَقُولُ الَّذِينَ آمَنُوا لَوْلَا نُزِّلَتْ سُورَةٌ فَإِذَا أُنْزِلَتْ سُورَةٌ
      مُحْكَمَةٌ وَذُكِرَ فِيهَا الْقِتَالُ رَأَيْتَ الَّذِينَ فِي قُلُوبِهِمْ مَرَضٌ
      يَنْظُرُونَ إِلَيْكَ نَظَرَ الْمَغْشِيِّ عَلَيْهِ مِنَ الْمَوْتِ فَأَوْلَى لَهُمْ '
  - type: update
    segment_index: '047.0027'
    new_start_seconds: 262.4
    new_tarteel_transcript:
    - طَاعَةٌ وَقَوْلٌ مَعْرُوفٌ فَإِذَا عَزَمَ الْأَمْرُ فَلَوْ صَدَقُوا اللَّهَ
      لَكَانَ خَيْرًا لَهُمْ
  - type: update
    segment_index: '061.0015'
    new_tarteel_transcript:
    - فَأَيَّدْنَا الَّذِينَ آمَنُوا عَلَىٰ عَدُوِّهِمْ فَأَصْبَحُوا ظَاهِرِينَ
