configs:
- id: '0.0'
  operations:
  - type: update
    segment_index: '000.0133'
    new_tarteel_transcript:
    - هِيَ حَسْبُهُمْ
  - type: update
    segment_index: '008.0039'
    new_audio_file: 0.0/008_0039.wav
  - type: delete
    segment_index: '008.0040'
  - type: delete
    segment_index: '009.0042'
  - type: delete
    segment_index: '009.0043'
  - type: update
    segment_index: '009.0133'
    new_tarteel_transcript:
    - هِيَ حَسْبُهُمْ
  - type: update
    segment_index: '011.0205'
    new_audio_file: 0.0/011.0205.wav
  - type: delete
    segment_index: '011.0206'
  - type: update
    segment_index: '016.0047'
    new_audio_file: 0.0/016_0047.wav
  - type: delete
    segment_index: '016.0048'
  - type: update
    segment_index: '016.0165'
    new_audio_file: 0.0/016_0165.wav
    new_tarteel_transcript:
    - إِنَّمَا يَفْتَرِي الْكَذِبَ الَّذِينَ لَا يُؤْمِنُونَ بِآيَاتِ اللَّهِ وَأُولَٰئِكَ
      هُمُ الْكَاذِبُونَ ‎
  - type: delete
    segment_index: '016.0166'
  - type: update
    segment_index: '019.0069'
    new_audio_file: 0.0/019_0069.wav
  - type: delete
    segment_index: '019.0070'
  - type: update
    segment_index: '026.0146'
    new_audio_file: 0.0/026_0146.wav
  - type: delete
    segment_index: '026.0147'
  - type: update
    segment_index: '037.0181'
    new_audio_file: 0.0/037_0181.wav
  - type: delete
    segment_index: '037.0182'
  - type: update
    segment_index: '039.0097'
    new_audio_file: 0.0/039_0097.wav
  - type: delete
    segment_index: '039.0098'
  - type: update
    segment_index: '042.0032'
    new_audio_file: 0.0/042_0032.wav
  - type: delete
    segment_index: '042.0033'
  - type: update
    segment_index: '053.0034'
    new_tarteel_transcript:
    - الَّذِينَ يَجْتَنِبُونَ كَبَائِرَ الْإِثْمِ وَالْفَوَاحِشَ إِلَّا اللَّمَمَ
  - type: update
    segment_index: '056.0096'
    new_audio_file: 0.0/056_0096.wav
    new_tarteel_transcript:
    - فَسَبِّح بِاسمِ رَبِّكَ العَظيمِ
  - type: delete
    segment_index: '056.0097'
  - type: update
    segment_index: '059.0028'
    new_audio_file: 0.0/059_0028.wav
  - type: delete
    segment_index: '059.0029'
  - type: update
    segment_index: '068.0048'
    new_audio_file: 0.0/068_0048.wav
  - type: delete
    segment_index: '068.0049'
  - type: update
    segment_index: '096.0012'
    new_audio_file: 0.0/096_0012.wav
    new_tarteel_transcript:
    - أَو أَمَرَ بِالتَّقوىٰ
  - type: delete
    segment_index: '096.0013'
- id: '0.1'
  operations:
  - type: update
    segment_index: '004.0061'
    new_audio_file: 0.1/004_0061.wav
    new_tarteel_transcript:
    - وَإِن أَرَدتُمُ استِبدالَ زَوجٍ مَكانَ زَوجٍ وَآتَيتُم إِحداهُنَّ قِنطارًا فَلا
      تَأخُذوا مِنهُ شَيئًا
  - type: delete
    segment_index: '004.0062'
  - type: update
    segment_index: '006.0210'
    new_audio_file: 0.1/006_0210.wav
    new_tarteel_transcript:
    - ' لَقَد تَقَطَّعَ بَينَكُم وَضَلَّ عَنكُم ما كُنتُم تَزعُمونَ'
  - type: delete
    segment_index: '006.0211'
  - type: update
    segment_index: '006.0375'
    new_audio_file: 0.1/006_0375.wav
  - type: delete
    segment_index: '006.0376'
  - type: update
    segment_index: '009.0035'
    new_audio_file: 0.1/009_0035.wav
    new_tarteel_transcript:
    - أَم حَسِبتُم أَن تُترَكوا وَلَمّا يَعلَمِ اللَّهُ الَّذينَ جاهَدوا مِنكُم وَلَم
      يَتَّخِذوا
  - type: delete
    segment_index: '009.0036'
  - type: update
    segment_index: '009.0248'
    new_audio_file: 0.1/009_0248.wav
    new_tarteel_transcript:
    - وَالَّذينَ اتَّخَذوا مَسجِدًا ضِرارًا وَكُفرًا وَتَفريقًا بَينَ المُؤمِنينَ
      وَإِرصادًا لِمَن حارَبَ اللَّهَ وَرَسولَهُ مِن قَبلُ وَلَيَحلِفُنَّ
  - type: delete
    segment_index: '009.0249'
  - type: update
    segment_index: '012.0098'
    new_audio_file: 0.1/012_0098.wav
    new_tarteel_transcript:
    - ثُمَّ يَأتي مِن بَعدِ ذٰلِكَ سَبعٌ شِدادٌ يَأكُلنَ ما قَدَّمتُم لَهُنَّ إِلّا
      قَليلًا مِمّا تُحصِنونَ
  - type: delete
    segment_index: '012.0099'
  - type: update
    segment_index: '012.0138'
    new_tarteel_transcript:
    - ' عَلَيهِ تَوَكَّلتُ'
  - type: update
    segment_index: '028.0064'
    new_audio_file: 0.1/028_0064.wav
    new_tarteel_transcript:
    - وَأَخي هارونُ هُوَ أَفصَحُ مِنّي لِسانًا فَأَرسِلهُ مَعِيَ رِدءًا يُصَدِّقُني
  - type: delete
    segment_index: '028.0065'
  - type: update
    segment_index: '038.0079'
    new_tarteel_transcript:
    - 'هَٰذَا '
  - type: update
    segment_index: '043.0029'
    new_audio_file: 0.1/043_0029.wav
  - type: delete
    segment_index: '043.0030'
  - type: update
    segment_index: '043.0126'
    new_audio_file: 0.1/043_0126.wav
    new_tarteel_transcript:
    - فَاصْفَحْ عَنْهُمْ وَقُلْ سَلَامٌ
  - type: delete
    segment_index: '043.0127'
  - type: update
    segment_index: '053.0037'
    new_tarteel_transcript:
    - الَّذِينَ يَجْتَنِبُونَ كَبَائِرَ الْإِثْمِ وَالْفَوَاحِشَ إِلَّا اللَّمَمَ
- id: '0.2'
  operations:
  - type: update
    segment_index: '038.0067'
    new_tarteel_transcript:
    - هَٰذَا
- id: '0.3'
  operations:
  - type: delete
    segment_index: '002.0602'
  - type: update
    segment_index: '002.0601'
    new_audio_file: 0.3/002_0601.wav
    new_tarteel_transcript:
    - 'فَهَدَى اللَّهُ الَّذِينَ آمَنُوا لِمَا اخْتَلَفُوا فِيهِ مِنَ الْحَقِّ بِإِذْنِهِ '
  - type: delete
    segment_index: '003.0361'
  - type: update
    segment_index: '003.0360'
    new_audio_file: 0.3/003_0360.wav
    new_tarteel_transcript:
    - وَمَا كَانَ قَوْلَهُمْ إِلَّا أَن قَالُوا رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا
      وَإِسْرَافَنَا فِي أَمْرِنَا وَثَبِّتْ أَقْدَامَنَا
  - type: delete
    segment_index: '004.0011'
  - type: update
    segment_index: '004.0010'
    new_audio_file: 0.3/004_0010.wav
    new_tarteel_transcript:
    - وَإِنْ خِفْتُمْ أَلَّا تُقْسِطُوا فِي الْيَتَامَىٰ فَانكِحُوا مَا طَابَ لَكُم
  - type: update
    segment_index: '006.0190'
    new_audio_file: 0.3/006_0190.wav
  - type: delete
    segment_index: '009.0054'
  - type: update
    segment_index: '009.0053'
    new_audio_file: 0.3/009_0053.wav
    new_tarteel_transcript:
    - الَّذِينَ آمَنُوا وَهَاجَرُوا وَجَاهَدُوا فِي سَبِيلِ اللَّهِ بِأَمْوَالِهِمْ
      وَأَنفُسِهِمْ أَعْظَمُ دَرَجَةً
  - type: update
    segment_index: '009.0198'
    new_tarteel_transcript:
    - هِيَ حَسْبُهُمْ
  - type: delete
    segment_index: '011.0077'
  - type: update
    segment_index: '011.0076'
    new_audio_file: 0.3/011_0076.wav
  - type: delete
    segment_index: '012.0163'
  - type: update
    segment_index: '012.0162'
    new_audio_file: 0.3/012_0162.wav
    new_tarteel_transcript:
    - عَلَيْهِ تَوَكَّلْتُ وَعَلَيْهِ فَلْيَتَوَكَّلِ الْمُتَوَكِّلُونَ
  - type: update
    segment_index: '016.0110'
    new_tarteel_transcript:
    - فَتَمَتَّعُوا
  - type: delete
    segment_index: '022.0176'
  - type: update
    segment_index: '022.0175'
    new_audio_file: 0.3/022_0175.wav
    new_tarteel_transcript:
    - ' يَكَادُونَ يَسْطُونَ بِالَّذِينَ يَتْلُونَ عَلَيْهِمْ آيَاتِنَا'
  - type: delete
    segment_index: '024.0064'
  - type: update
    segment_index: '024.0063'
    new_audio_file: 0.3/024_0063.wav
  - type: update
    segment_index: '022.0193'
    new_tarteel_transcript:
    - هُوَ اجْتَبَاكُمْ
  - type: delete
    segment_index: '054.0070'
  - type: delete
    segment_index: '088.0022'
  - type: update
    segment_index: '088.0021'
    new_audio_file: 0.3/088_0021.wav
    new_tarteel_transcript:
    - فَذَكِّرْ إِنَّمَا أَنتَ مُذَكِّرٌ
