configs:
  - id: "0.0"
    operations:
      - type: delete
        segment_index: "008.0040"
      - type: update
        segment_index: "008.0039"
        new_audio_file: 0.0/008_0039.wav

      - type: delete
        segment_index: "009.0043"
      - type: delete
        segment_index: "009.0042"

      - type: update
        segment_index: "000.0133"
        new_tarteel_transcript: "هِيَ حَسْبُهُمْ"

      - type: delete
        segment_index: "011.0206"
      - type: update
        segment_index: "011.0205"
        new_audio_file: 0.0/011.0205.wav

