# Training configuration example
train_moshaf_ids:
  - "0.0"
  - "0.1"
  - "0.2"
  - "0.3"
  - "1.0"
  - "2.0"
  - "2.1"
  - "3.0"
  - "4.0"
  - "5.0"
  - "6.0"
  - "7.0"
  - "8.0"
  - "9.0"
  - "11.0"
  - "12.0"
  - "13.0"
  - "22.0"
  - "24.0"
  - "26.0"
  - "27.0"
  - "28.0"
  - "29.0"
  - "30.0"

# Test moshaf IDs (optional)
test_moshaf_ids:
  - "19.0"
  - "26.1"


# Loss
loss_weights:
  phonemes: 0.4
  shidda_or_rakhawa: 0.068
  tafkheem_or_taqeeq: 0.063


# Augmentaion
augment_prob: 0.4
max_audio_seconds: 30.0

# Training parameters
num_epochs: 1
learning_rate: 5e-5
seed: 42

# Batch sizes
per_device_train_batch_size: 64
pre_device_eval_batch_size: 64

# Dataset parameters
devset_ratio: 0.1
save_every: 0.2

# Hardware settings
# num_workers: 4

# Optimizer settings
weight_decay: 0.01
warmup_ratio: 0.2

# Model saving and evaluation
metric_for_bet_model: "average_per"
greater_is_better: false

hub_model_id: "obadx/muaalem-model-v2"
wandb_project_name: "muaalem-model-v2"

# Gradient checkpointing
gradient_checkpoiniting: true
