# Training configuration example
train_moshaf_ids:
  # - "0.0"
  # - "0.1"
  # - "0.2"
  - "0.3"
  # - "1.0"
  # - "2.0"
  # - "2.1"
  # - "3.0"

# Test moshaf IDs (optional)
# test_moshaf_ids:
#   - "moshaf_005"
#   - "moshaf_006"


# Loss
phonemes_loss_weight: 1.0

# Augmentaion
augment_prob: 0.4
max_audio_seconds: 20.0

# Training parameters
num_epochs: 1
learning_rate: 1e-4
seed: 42

# Batch sizes
per_device_train_batch_size: 1
pre_device_eval_batch_size: 1

# Dataset parameters
devset_ratio: 0.1
save_every: 0.5

# Hardware settings
# num_workers: 4

# Optimizer settings
weight_decay: 0.01
warmup_ratio: 0.2

# Model saving and evaluation
metric_for_bet_model: "average_per"
greater_is_better: false

hub_model_id: "obadx/Muaalem-model-dev"
wandb_project_name: "Muaalem-model-dev"

# Gradient checkpointing
gradient_checkpoiniting: true
