items:
  - id: "0.0"
    turnc_ms: 230

  - id: "1.0"
    turnc_ms: 340

  - id: "2.1"
    turnc_ms: 310

  - id: "3.0"
    turnc_ms: 360

  - id: "5.0"
    turnc_ms: 210

  - id: "6.0"
    turnc_ms: 240

  - id: "7.0"
    turnc_ms: 635

  - id: "9.0"
    turnc_ms: 390

  - id: "11.0"
    turnc_ms: 535

  - id: "12.0"
    turnc_ms: 90

  - id: "13.0"
    turnc_ms: 220

  - id: "17.0"
    turnc_ms: 355

  - id: "19.0"
    turnc_ms: 110

  - id: "21.0"
    turnc_ms: 370

  - id: "21.1"
    turnc_ms: 390

  - id: "22.0"
    turnc_ms: 330

  - id: "24.0"
    turnc_ms: 275

  - id: "25.0"
    turnc_ms: 345

  - id: "26.1"
    turnc_ms: 190

  - id: "27.0"
    turnc_ms: 200

  - id: "31.0"
    turnc_ms: 240
